### ISSUE TITLE
pointnet-autoencoder-pytorch

### ISSUE THREAD

**Issue by JieLi1994** [dhirajsuvarna/pointnet-autoencoder-pytorch#1]
Hi, I found your repository: [pointnet-autoencoder-pytorch](https://github.com/dhirajsuvarna/pointnet-autoencoder-pytorch).
I want to know if it can run normally and get effective result. Thanks for your code

**Comment by dhirajsuvarna** [comment]
@JieLi1994, thanks for using the code.
I did write this for my own purpose and didn't think anyone else will use it, so didn't make it useable as is.

However let me know if there are any problems you face, would like to help.
